<a href="https://colab.research.google.com/github/PinkOrangeSapphire/229352/blob/main/Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [6]:
a = torch.tensor(2)
print(a)

tensor(2)


In [8]:
b = torch.tensor(3)
print(a*b)

tensor(6)


### Convert a tensor to scalar

In [9]:
c = b.item()
print(c)

3


### Creating 2D tensor

In [11]:
A = torch.tensor([[4, 9], [5, 6]])
A

tensor([[4, 9],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [12]:
B = A.numpy()
B

array([[4, 9],
       [5, 6]])

### Convert from numpy array to tensor

In [13]:
C = torch.from_numpy(B)
C

tensor([[4, 9],
        [5, 6]])

## PyTorch and GPU

check if GPU is available

In [14]:
torch.cuda.is_available()

True

In [16]:
C.device

device(type='cpu')

In [18]:
D  = C.cuda()
D.device

device(type='cuda', index=0)

In [19]:
E = D.cpu().numpy()
E

array([[4, 9],
       [5, 6]])

## Basic operations

In [21]:
E-2

array([[2, 7],
       [3, 4]])

In [20]:
E * 2

array([[ 8, 18],
       [10, 12]])

In [22]:
D.cpu() * np.array ([1, 2])

/tmp/ipython-input-4090808032.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array ([1, 2])


tensor([[ 4, 18],
        [ 5, 12]])

### Matrix multiplication

In [24]:
A = torch.tensor([[4, 9], [5, 2]])
B = torch.tensor([[5, 4], [5, 8]])

torch.matmul(A, B)

tensor([[65, 88],
        [35, 36]])

In [25]:
torch.mm(A, B)

tensor([[65, 88],
        [35, 36]])

In [26]:
A@B

tensor([[65, 88],
        [35, 36]])

### Matrix transpose

In [27]:
A

tensor([[4, 9],
        [5, 2]])

In [28]:
A.t()

tensor([[4, 5],
        [9, 2]])

## Creating a specific type of tensor

In [29]:
a = torch.zeros(1, 2, 3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [30]:
b  = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [31]:
i = torch.eye(3)
i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [32]:
R1 = torch.rand(2,3)
R1

tensor([[0.5338, 0.1216, 0.0418],
        [0.4771, 0.0143, 0.1294]])

In [33]:
R2 = torch.randn(2,3)
R2

tensor([[-1.1126,  2.0273,  1.5934],
        [-0.6038, -0.4152,  2.0314]])

In [34]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

### Checking the shape of a tensor

In [35]:
A.shape

torch.Size([2, 2])

In [37]:
A.size()

torch.Size([2, 2])

### Changing the shape of a tensor

In [39]:
u =  torch.arange(6)
u.shape

torch.Size([6])

In [40]:
v = u.reshape(2, 3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [41]:
w = u.view(3,2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [42]:
a = torch.arange(4)
b = torch.arange(4) + 1
c = torch.stack((a, b), axis = 0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [44]:
# concatenate
e = torch.cat([a,b], axis = 0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [47]:
a_2d = a.unsqueeze(1)
b_2d = b.unsqueeze(1)
e = torch.cat([a_2d, b_2d], axis = 1)
print(e)

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])


### Squeezing a tensor (removing an extra dimension)

In [48]:
A = torch.zeros(1, 2 , 3)
B = A.squeeze()

In [49]:
A.shape

torch.Size([1, 2, 3])

In [50]:
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [51]:
# H.shape = (6, )
C = B.unsqueeze(axis = 0)
C.shape

torch.Size([1, 2, 3])

## Indexing

In [52]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [53]:
torch.inverse(torch.tensor([[2.0, 0.0], [0.0, 5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

##Create random tensors



In [55]:
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

print(f"X shape: {X.shape}")
print(f"b shape: {b.shape}")
print(f"e shape: {e.shape}")

X shape: torch.Size([200, 7])
b shape: torch.Size([8, 1])
e shape: torch.Size([200, 1])


## Create a tensor of ones



In [56]:
ones_tensor = torch.ones(200, 1)

print(f"ones_tensor shape: {ones_tensor.shape}")

ones_tensor shape: torch.Size([200, 1])


## Modify tensor X



In [57]:
X = torch.cat((ones_tensor, X), axis=1)

print(f"Modified X shape: {X.shape}")
print(f"First 5 rows of modified X:\n{X[:5]}")

Modified X shape: torch.Size([200, 8])
First 5 rows of modified X:
tensor([[ 1.0000, -0.4375, -0.1129,  0.0054,  0.1646, -0.4157, -0.3596, -1.2821],
        [ 1.0000,  0.4476,  1.3777,  0.0923,  0.7791,  0.5561,  0.7627, -1.3618],
        [ 1.0000,  0.0715,  0.4646, -2.2860,  0.2674, -1.2924,  0.9033, -0.7393],
        [ 1.0000, -0.6191,  1.0782,  0.3178,  1.5065,  0.0905, -0.0046,  1.4945],
        [ 1.0000, -1.3875, -0.1116,  0.1591, -1.1556,  0.6800,  0.7270,  0.0079]])


## Compute y


In [58]:
y = torch.matmul(X, b) + e

print(f"y shape: {y.shape}")
print(f"First 5 rows of y:\n{y[:5]}")

y shape: torch.Size([200, 1])
First 5 rows of y:
tensor([[ 1.9645],
        [ 0.8677],
        [ 0.0306],
        [ 2.2646],
        [-2.1752]])


## Fit linear regression and estimate coefficients


In [59]:
X_T = X.T
X_T_X = torch.matmul(X_T, X)
X_T_X_inv = torch.inverse(X_T_X)
X_T_y = torch.matmul(X_T, y)
b_hat = torch.matmul(X_T_X_inv, X_T_y)

print(f"b_hat shape: {b_hat.shape}")
print(f"Estimated coefficients b_hat:\n{b_hat}")

b_hat shape: torch.Size([8, 1])
Estimated coefficients b_hat:
tensor([[ 0.6238],
        [ 0.3801],
        [ 0.5690],
        [-0.6742],
        [ 0.1539],
        [ 0.0979],
        [-1.6331],
        [-0.1486]])


## Compute predictions y_hat


In [60]:
y_hat = torch.matmul(X, b_hat)

print(f"y_hat shape: {y_hat.shape}")
print(f"First 5 rows of y_hat:\n{y_hat[:5]}")

y_hat shape: torch.Size([200, 1])
First 5 rows of y_hat:
tensor([[ 1.1520],
        [ 0.6467],
        [ 1.0059],
        [ 0.8139],
        [-1.3740]])


## Calculate MSE



In [61]:
y_np = y.numpy()
y_hat_np = y_hat.numpy()

mse = np.mean((y_np - y_hat_np)**2)

print(f"MSE: {mse}")

MSE: 0.8599699139595032
